### ISSUE TITLE
Cellular Patch should match image-customization

### ISSUE THREAD

**Issue by seilpforte** [ffac/site#105]
https://github.com/ffac/site/blob/1c644eed9f8cc34603278fe1955ce85d9ee9f290/patches/cellular.patch#L1-L24

Both lists should match ([ref](https://github.com/ffac/site/blob/1c644eed9f8cc34603278fe1955ce85d9ee9f290/image-customization.lua#L37-L45))
* zte,mf281
* glinet,gl-xe300
* glinet,gl-ap1300
* zte,mf289f
* zte,mf286r
* wavlink,ws-wn572hp3-4g
* tplink,tl-mr6400-v5

**Comment by grische** [comment]
I guess the patch in question that needs appending is this one: https://github.com/ffac/site/blob/v2023.2.x/patches/targets-ath79-nand.patch

Any reason this device is not upstreamed yet?

**Comment by maurerle** [comment]
This is fixed with d81245b411c92d9b24550c40419b5adea941d5b5

**Comment by maurerle** [comment]
@grische the device is not tested yet. We are just building firmware, but noone did the checklist yet.
