### ISSUE TITLE
Mesh BSSID 2.4 und 5GHz konsitent machen

### ISSUE THREAD

**Issue by mmalte** [ffac/site#26]
Falls wir vor 802.11s eine Anpassung am Mesh vornehmen die nur von den Blättern aus durchgeführt werden kann sollten wir auch die Mesh BSSID angleichen:

Aktueller Stand:
2.4GHz: CA:FF:24:FF:AC:24
5.2GHz: CA:FE:52:FF:AC:52

Da die 2.4GHz BSSID die kritischere ist sollte diese konstant bleiben, auch wenn sie die weniger Schöne ist:
2.4GHz: CA:FF:24:FF:AC:24
5.2GHz: CA:FF:52:FF:AC:52

**Comment by jannic** [comment]
Ich würde das gar nicht anfassen - aber einen passenden Kommentar dran machen (s. commit 34d4c3e)

**Comment by mmalte** [comment]
5GHz mesh ist ab branch v2019.1.x umgestellt auf 802.11s damit entfällt die mac
