### ISSUE TITLE
Kontaktdate auch bei lede branch entfernen

### ISSUE THREAD

**Issue by mmalte** [ffac/site#43]
https://github.com/ffac/ffac-status-page-api muss wohl für lede entsprechend neu erstellt werden.

**Comment by mmalte** [comment]
@jannic was meinst du? Müssen wir die Kontaktdaten aus der Statusseite entfernen?

**Comment by jannic** [comment]
Schwierig. Einerseits ist das Security by Obscurity, wer weiß was er tut kommt so oder so über respondd an die Daten. Außerdem ist die Angabe freiwillig, wer seine Daten da angibt tut das ja gerade, damit er erreicht werden kann. Das spricht für die Anzeige auf der Kontaktseite.
Andererseits haben wir das bisher da nicht angezeigt, und es ist denkbar, dass sich einzelne Router-Betreiber darauf verlassen, dass das so bleibt.
IMHO können wir für neu installierte Router die Kontaktdaten anzeigen, wenn wir das vorher entsprechend kommunizieren, aber bei alten Routern die auf eine neue Version updated werden, können wir das nicht einfach anzeigen.
Sauberste Lösung wäre eine Konfigurationsoption, die der Nutzer selber setzen kann. Bei Neuinstallationen kann die default auf 'anzeigen' stehen, aber bei Updates von älteren Versionen muss sie auf 'nicht anzeigen' stehen.
Das erscheint mir aber recht viel Aufwand. Daher vielleicht der Einfachheit halber auf 'nicht anzeigen' bleiben?

**Comment by mmalte** [comment]
Der Text unter dem man seine Kontaktdaten hinterlegt hat war folgender:

> msgid ""
> "Please provide your contact information here to allow others to contact "
> "you. Note that this information will be visible <em>publicly</em> on "
> "the internet together with your node's coordinates."
> msgstr ""
> "Bitte hinterlege hier einen Hinweis, um anderen zu ermöglichen, "
> "Kontakt mit dir aufzunehmen. Beachte, dass dieser Hinweis auch "
> "<em>öffentlich</em> im Internet, zusammen mit den Koordinaten "
> "deines Knotens, einsehbar sein wird." 

Also der unveränderte aus:
https://github.com/freifunk-gluon/gluon/blob/v2016.2.x/package/gluon-config-mode-contact-info/i18n/de.po

Da bei uns aber im vergleich zu anderen communities recht viele Kontaktdaten hinterlegt sind (ich habe das im Sommer mal mit anderen verglichen) scheint es etwas bewirkt zu haben, dass wir in der Praxis gefiltert haben.

Die experimental würde ich trotzdem ins autoupdate geben, da diese Knoten sowieso schon ohne den Filter sind. Für eine beta & stable mit Filter bräuchten wir eine Anpassung wie du sie in 34ca3da5abdf41f7d0761149f5a1bc86f722668b gemacht hattest. Kannst du das wieder übernehmen?

**Comment by mmalte** [comment]
Da keine automatische Verlinkung erfolgt ist:
https://github.com/ffac/ffac-status-page-api/commit/34ca3da5abdf41f7d0761149f5a1bc86f722668b

**Comment by mmalte** [comment]
in 5b25de444f83aa8dd95656e3e4e8b673c8396dec gelöst.
