### ISSUE TITLE
Update-Pfad 2016.2.7 -> 2018.2.x für CPEs etc. definieren

### ISSUE THREAD

**Issue by jannic** [ffac/site#63]
Auf CPEs und ein paar anderen Geräten funktioniert das direkte Update von der letzten Stable-Firmware 2016.2.7-1-stable auf aktuelle Firmwares (OpenWRT >= v18.06.0-rc1, Gluon >= v2018.2) nicht, da diese eine Änderung in der Partitionierung beinhalten (Commit 373dc11b519516682ab48bf7db501ffffced4e61), wodurch die alte Firmware im neuen Image eine beim Überprüfen der Kompatibilität benötigte Datenstruktur nicht findet.

Damit ein Update funktioniert, muss zunächst eine Firmware installiert werden, die den Patch "ar71xx: sysupgrade: improve CPE/WBS 210/510 validation, add new metadata offset" enthält, aber noch nicht die Änderung an der Partitionierung. Das bedeutet 

In Frage kämen dafür:
1) eine von uns gepatchte 2016.2.7-1-stable mit einem Backport des Patches
2) Gluon >= v2017.1.6 und < v2018.2, z.B. v2017.1.6 oder v2018.1.4

Möglichkeit 1) habe ich auf einem Gerät getestet und sie erscheint mir relativ sicher zu sein, da wir nur eine kleine Änderung an der lange getesteten Firmware vornehmen.

Möglichkeit 2) hätte dagegen den Vorteil, dass wir keine selbstgepatchte Version verwenden müssten.

Beide Möglichkeiten lassen sich nicht mehr ohne weiteres als Experimental ausrollen, da wir dort schon auf 2018.2 sind und somit ein Downgrade durchführen müssten. Das ist erstens gefährlich (nicht offiziell Supportet, bei einem Test für 2018.2.1 -> 2016.2.7 schlug es fehl) und zweitens nur mit Klimmzügen möglich.

**Comment by jannic** [comment]
Patch für Variante 1) liegt unter https://github.com/ffac/gluon/tree/v2016.2-to-v2018.2-upgrade-path

**Comment by mmalte** [comment]
Mittlerweile wurde der Patch in die v2016.2.x aufgenommen, ich würde daher vorschlagen für wbs&cpe einen build auf Basis von v2016.2.x zu erstellen.
https://gluon.readthedocs.io/en/v2019.1/releases/v2019.1.html
Gluon 2019.1
Important notes
<...>
If you are upgrading from a version prior to v2018.1, please note that the flash layout on some devices (TP-Link CPE/WBS 210/510) was changed. To avoid upgrade failures, make sure to upgrade to Gluon 2017.1.8 or the latest Gluon 2016.2.x (unreleased) before installing Gluon 2018.1, 2018.2 or 2019.1.

Für die Zukunft habe ich nun immer den update pfad ergänzt: -from-"branch" (bsp: http://updates.freifunk-aachen.de/from-2018.2.x/stable/sysupgrade)

Das wird jetzt etwas gefummel mit der aktuellen manifest Datei die noch unter http://updates.freifunk-aachen.de/from-2018.2.x/stable/sysupgrade liegt, folgender zeitlicher Ablauf schwebt mir vor:

||wbs&cpe|rest|
| ------------- | ------------- |------------- |
|aktuell|2016.2.7-1-stable|2016.2.7-1-stable|
|übergang|2016.2.x-1-stable|2016.2.7-1-stable|
|v2018.2.3 released|2016.2.x-1-stable|2018.2.3-1-stable|

Images mit 2016.2.x-1-stable suchen dann unter dem Pfad from-2016.2.x nach weiteren updates, die mit 2018.2.3-1-stable in from-2018.2.x, somit sollten nur noch Altknoten die ursprüngliche URL abfragen.

**Comment by mmalte** [comment]
es werden nun immer je major release neue update pfade hinterlegt.
