### ISSUE TITLE
test eulenfunk-hotfix package

### ISSUE THREAD

**Issue by mmalte** [ffac/site#69]
Ich sehe auf der Karte immer wieder Mesh Knoten die noch mit einem 0-5% link zu sehen sind, aber nicht erreicht werden können.
Mindestens diese Knoten könnten wir mit solch einem Paket schnell wiederbeleben:

https://github.com/ffac/eulenfunk-packages/tree/v2019.1.x/eulenfunk-hotfix/files/lib/gluon/eulenfunk-hotfix

**Comment by maurerle** [comment]
With our v2023.1.x firmware I have not yet seen such things, though I think we can close this issue?
If this arises again, we can reopen it or much rather find a more modern fix :)
