### ISSUE TITLE
Add license information to the repo

### ISSUE THREAD

**Issue by tyll** [ffac/site#7]
The contents of this repository should be licensed somehow to formally allow its distribution. I propose to use the same license as gluon to keep things easy:
https://github.com/freifunk-gluon/gluon/blob/master/LICENSE

**Comment by mmalte** [comment]
Ups, I did not notice the issue until today, using the same license as gluon is a very good idea.

**Comment by mmalte** [comment]
@yayachiken spricht etwas dagegen das Lizenz File vom ssid-changer zu übernehmen?

**Comment by yayachiken** [comment]
Kommt drauf an. Soll Namensnennung bei Verwendung einer site.conf notwendig sein?

Wenn ja, dann ist die Lizenz ok (ist ja die gluon-lizenz) und ich kann nen PR machen.
Wenn nein, dann wäre ich tatsächlich eher für Creative-Commons Zero, dann darf man einfach machen was man will (vgl. ffac-api-file)

**Comment by mmalte** [comment]
Creative-Commons Zero sollte passen.

Wobei mir auch unklar ist was die anderen communities so haben, insbesondere bin ich mir unser wer es ursprünglich geschrieben hat.

Ich vermute es war die config vom Rheinufer.
